apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: toto
  MYSQL_PASSWORD: toto
  MYSQL_DATABASE: wordpress
